repos:
    # Actualizamos dependencias y export
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.17
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.17
    hooks:
      - id: uv-export
        args: ["--frozen", "--no-hashes", "--output-file=requirements.txt", "--quiet"]
    # Validamos tests
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: ./.venv/bin/pytest
        language: system
        pass_filenames: false
        always_run: true
   