services:
  docdb:
    image: mongodb/mongodb-community-server
    container_name: docdb
    ports:
    - 27017:27017

  minio:
    image: minio/minio
    container_name: minio1
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /mnt/data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"